[features]
seeds = false

[programs.localnet]
auction_house = "FpuKSiZ5j5Qu68X2QB2Ji2BcYpPptSX2Pmv7EFAcZiF2"

[programs.devnet]
auction_house = "FpuKSiZ5j5Qu68X2QB2Ji2BcYpPptSX2Pmv7EFAcZiF2"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/auction.json"

[scripts]
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/auction-house.ts"
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/stress-tests.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/cranks-tests.ts"

[test]
startup_wait = 100000
